# Generated by Django 5.1.3 on 2024-11-28 07:33

from django.db import migrations


def create_specializations(apps, schema_editor):
    Specialization = apps.get_model('accounts', 'Specialization')
    specializations = [
        'General Practitioner (GP) / Family Physician',
        'Cardiologist',
        'Dermatologist',
        'Neurologist',
        'Orthopedic Surgeon',
        'Pediatrician',
        'Gynecologist / Obstetrician (OB-GYN)',
        'Oncologist',
        'Psychiatrist',
        'Endocrinologist',
        'Ophthalmologist',
        'ENT Specialist (Otolaryngologist)',
        'Pulmonologist',
        'Gastroenterologist',
        'Hematologist',
        'Nephrologist',
        'Urologist',
        'Rheumatologist',
        'Surgeon (General Surgeon, Specialized Surgeons)',
        'Radiologist',
        'Anesthesiologist',
        'Pathologist',
        'Geriatrician',
        'Immunologist / Allergist',
        'Emergency Medicine Physician'
    ]
    
    for spec in specializations:
        Specialization.objects.create(name=spec)

def remove_specializations(apps, schema_editor):
    Specialization = apps.get_model('accounts', 'Specialization')
    Specialization.objects.all().delete()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]


    operations = [
        migrations.RunPython(create_specializations, remove_specializations),
    ]